<?php

namespace BackBundle\Repository;

/**
 * NewsTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
